name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  firebase: ^9.0.2
  firebase_auth: ^3.3.8
  firebase_core: ^1.11.0
  google_fonts: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - images/home.jfif
    - images/signup.jfif
    - images/logo.jpg

