// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq-_8uHb2B5iWXJ8flehhm1EOTEtDBK_8',
    appId: '1:898109643759:web:e6ae2e7b5bdd54f16bb41a',
    messagingSenderId: '898109643759',
    projectId: 'fitness-app-ddc22',
    authDomain: 'fitness-app-ddc22.firebaseapp.com',
    storageBucket: 'fitness-app-ddc22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeLYlWzA0AXZTpga7x-lC8TYQ6UjHotos',
    appId: '1:898109643759:android:454a8edd881232f46bb41a',
    messagingSenderId: '898109643759',
    projectId: 'fitness-app-ddc22',
    storageBucket: 'fitness-app-ddc22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEmLXonFWFLCg3q6RAlWWBAJFjlBtNma4',
    appId: '1:898109643759:ios:f4f65638cba2214f6bb41a',
    messagingSenderId: '898109643759',
    projectId: 'fitness-app-ddc22',
    storageBucket: 'fitness-app-ddc22.appspot.com',
    iosClientId: '898109643759-q5qnef63utbimr60g6f7ppmcn3gbbghh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );
}
